# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc70f4aebd58b0c872e3e266da4a953fcf76b0fa4b249f45d34c18794ed7fb6f80abb04e429169e7f34a3946cfd5dae14efa40229de840fed81c19dfd2b9b3a

test:
  secret_key_base: a03d04d2f5a054b18b27074e95e737db5818d1a9c6b5a7fb2bdfe0949a4724bdcf2d1cab313ba472d7302f2d6e3871a14580bbb7bd64e9a80c8caba05e700982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
